<?php 

$setores = 
[
    ["Administração", "fa-user-tie"], 
    ["Almoxarifado", "fa-warehouse"],
    ["Ambulatório", "fa-hospital"],
    ["Auditoria de Enfermagem", "fa-table"],
    ["Banco de Sangue", "fa-droplet"],
    ["CAF", "fa-capsules"],
    ["Capelania", "fa-church"],
    ["Central de Autorizações", "fa-key"],
    ["Central de Consultas", "fa-clipboard"],
    ["Centro Cirúrgico", "fa-stethoscope"],
    ["CME", "fa-soap"],
    ["Cobrança", "fa-landmark"],
    ["Compras", "fa-cart-shopping"],
    ["Comunicação", "fa-comments"],
    ["Contabilidade", "fa-calculator"],
    ["CTI", "fa-bed-pulse"],
    ["CTI 2", "fa-bed-pulse"],
    ["CTI 3", "fa-bed-pulse"],
    ["CTI 4", "fa-bed-pulse"],
    ["Custos", "fa-percent"],
    ["CVS", "fa-file"],
    ["Departamento Comercial", "fa-building"],
    ["Departamento Pessoal", "fa-building"],
    ["Diagnóstico Imagem", "fa-stethoscope"],
    ["Farmácia Central", "fa-prescription-bottle-medical"],
    ["Faturamento", "fa-file-invoice"],
    ["Financeiro", "fa-file-invoice-dollar"],
    ["Fisioterapia", "fa-user-doctor"],
    ["Gerência de Enfermagem", "fa-bars-progress"],
    ["Gestão de Leitos", "fa-bars-progress"],
    ["Hemodinâmica", "fa-user-doctor"],
    ["Hotelaria", "fa-user-doctor"],
    ["Informática", "fa-laptop-code"],
    ["Jardinagem", "fa-leaf"],
    ["Jurídico", "fa-scale-balanced"],
    ["Laboratório", "fa-flask"],
    ["Lavanderia", "fa-shirt"],
    ["Manutenção", "fa-hammer"],
    ["Marcenaria", "fa-tree"],
    ["NEP", "fa-users"],
    ["NEWENG", "fa-users"],
    ["NIR", "fa-briefcase"],
    ["OPME", "fa-person"],
    ["Ouvidoria", "fa-bullhorn"],
    ["Pronto Atendimento", "fa-ambulance"],
    ["Psicologia", "fa-ear-listen"],
    ["Qualidade", "fa-star"],
    ["Radiologia", "fa-x-ray"],
    ["Recepção", "fa-bell-concierge"],
    ["Recepção Ambulatório de Ortopedia", "fa-bell-concierge"],
    ["Recepção do Centro de Diagnósticos", "fa-bell-concierge"],
    ["Recepção Internação", "fa-bell-concierge"],
    ["Recepção Pronto Atendimento", "fa-bell-concierge"],
    ["Recurso de Glosa", "fa-file"],
    ["Recursos Humanos", "fa-user"],
    ["Repasse Médico", "fa-user-nurse"],
    ["SAME", null],
    ["SCIH", null],
    ["Serviço de Higiene e Limpeza", null],
    ["SESMT", null],
    ["SND", null],
    ["Supervisão de Enfermagem", null],
    ["Totalmedcare", null],
    ["Transplante", null],
    ["Transporte", null],
    ["Ultrassom", null],
    ["Unidade Internação 1ºAndar", null],
    ["Unidade Internação 2ºAndar", null],
    ["Unidade Internação Cirúrgica", null],
    ["Unidade Internação Clínica", null],
    ["Vigilância", null],
    ["Enfermaria", null]
]

?>