USE informatica;

-- OBS OS VALORES ANTES JÁ ERAM 0 TODOS SEM EXCESSÃO, ENTÃO NÃO USEI WHERE. ISSO FOI PARA REMOVER VALORES NULOS QUE ESTAVAM NO BANCO.
UPDATE computadores SET legendaI = 0;

-- OBS NÃO TINHA VALORES ANTES POR ISSO SEM WHERE
UPDATE computadores SET responsavel = 'Público';